// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvAQit8EbjAliQZyPuGcIncnzZhlWCRYw',
    appId: '1:477443104198:web:491c185d152064878926c7',
    messagingSenderId: '477443104198',
    projectId: 'picpost-eb66b',
    authDomain: 'picpost-eb66b.firebaseapp.com',
    storageBucket: 'picpost-eb66b.appspot.com',
    measurementId: 'G-7VPWFG302J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgL9DCGBYDk7aa-ByMqLSLs3Gh8TQAF9U',
    appId: '1:477443104198:android:51ea54b59875ef588926c7',
    messagingSenderId: '477443104198',
    projectId: 'picpost-eb66b',
    storageBucket: 'picpost-eb66b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4MNxm9bFBZInaLz_Dyn-DmjrowjNd3W8',
    appId: '1:477443104198:ios:ead034de7327f47a8926c7',
    messagingSenderId: '477443104198',
    projectId: 'picpost-eb66b',
    storageBucket: 'picpost-eb66b.appspot.com',
    iosBundleId: 'com.example.picPost',
  );
}
